{
 "title": "immich",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Immich version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "immich_server_info_version_number",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "User count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "immich_server_stats_user_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk space used by Immich",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(immich_server_stats_usage_by_users)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total disk size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "immich_server_info_totalDiskSize",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total disk size usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "immich_server_info_diskUse", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Remaining disk size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - immich_server_info_diskUsagePercentage",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "description": "amount of CPU usage over time",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
   "targets": [
    { "expr": "immich_system_info_loadAverage", "legendFormat": "{{period}}" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
   "targets": [
    { "expr": "immich_system_info_cpu_usage", "legendFormat": "CPU usage" }
   ]
  },
  {
   "title": "Free memory",
   "type": "timeseries",
   "description": "Free memory over time",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "immich_system_info_memory{type=\"Free\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Daily data growth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(immich_server_stats_usage_growth[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Weekly data growth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(immich_server_stats_usage_growth[1w])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk usage by user",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "immich_server_stats_usage_by_users",
     "legendFormat": "{{firstName}}"
    }
   ]
  },
  {
   "title": "Monthly data growth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(immich_server_stats_usage_growth[4w])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Yearly data growth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(immich_server_stats_usage_growth[1y])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Daily photos growth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(immich_server_stats_photos_growth[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Weekly photos growth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(immich_server_stats_photos_growth[1w])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total photos by user",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "immich_server_stats_photos_by_users",
     "legendFormat": "{{firstName}}"
    }
   ]
  },
  {
   "title": "Monthly photos growth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(immich_server_stats_photos_growth[4w])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Yearly photos growth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(immich_server_stats_photos_growth[1y])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Photos Growth",
   "type": "timeseries",
   "description": "amount of photos over time",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "delta(immich_server_stats_photos_by_users[4w])",
     "legendFormat": "{{firstName}}"
    }
   ]
  },
  {
   "title": "Photos Growth",
   "type": "timeseries",
   "description": "amount of photos over time",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "delta(immich_server_stats_photos_by_users[1y])",
     "legendFormat": "{{firstName}}"
    }
   ]
  },
  {
   "title": "Daily video growth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(immich_server_stats_videos_growth[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Weekly videos growth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(immich_server_stats_videos_growth[1w])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total videos by user",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "immich_server_stats_videos_by_users",
     "legendFormat": "{{firstName}}"
    }
   ]
  },
  {
   "title": "Monthly videos growth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(immich_server_stats_videos_growth[4w])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Yearly video growth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(immich_server_stats_videos_growth[1y])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Videos Growth",
   "type": "timeseries",
   "description": "amount of videos over time",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "delta(immich_server_stats_videos_by_users[4w])",
     "legendFormat": "{{firstName}}"
    }
   ]
  },
  {
   "title": "Videos Growth",
   "type": "timeseries",
   "description": "amount of videos over time",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "delta(immich_server_stats_videos_by_users[1y])",
     "legendFormat": "{{firstName}}"
    }
   ]
  }
 ]
}